spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/devgrindhub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: drop-create

# Logging Configuration (Optional)
logging:
  level:
    org:
      hibernate: DEBUG
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE


  #node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"

jwt:
  secret: 25955c56a0f61d70607323c6dfc53f3b6efdf7a91723bd6ddddf4ce7f1424669
  expiration: 86400000